fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user_create:
    pattern:  /
    defaults: { _controller: GSBPatientsBundle:Fosuser:index }
    
fos_user_profile_show_user:
    pattern: /profil/{id}
    defaults: { _controller: GSBPatientsBundle:Fosuser:show } 
    
fos_user_profile_new_user:
    pattern: /new
    defaults: { _controller: GSBPatientsBundle:Fosuser:new }

fos_user_profile_edit_user:
    pattern: /edit/{id}
    defaults: { _controller: GSBPatientsBundle:Fosuser:edit }
    
fos_user_profile_delete_user:
    pattern: /delete/{id}
    defaults: { _controller: GSBPatientsBundle:Fosuser:delete }
    
fos_user_profile_update_user:
    pattern: /update/{id}
    defaults: { _controller: GSBPatientsBundle:Fosuser:update }
    #method: post|delete