security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_MEDECIN, ROLE_SECRETAIRE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    medecin: { password: medecinpass, roles: [ 'ROLE_MEDECIN'] }
                    secretaire: { password: secretairepass, roles: ['ROLE_SECRETAIRE'] }
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    
        main:
            id: fos_user.user_provider.username
            

    firewalls:
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
       
        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /index
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret% 
                # %secret% est un paramètre de parameters.yml
                
    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/caisse, roles: ROLE_ADMIN }
        #- { path: ^/caisse, roles: ROLE_ADMIN }
        #- { path: ^/caisse, roles: ROLE_ADMIN }
        #- { path: ^/caisse, roles: ROLE_ADMIN }
        #- { path: ^/caisse, roles: ROLE_ADMIN }
        #- { path: ^/caisse, roles: ROLE_ADMIN }
        #- { path: ^/caisse, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    encoders:
        GSB\PatientsBundle\Entity\User: sha512